language: generic 

sudo: required
services:
  - docker

  before install:
    - docker build -t fmtech2014/docker-react -f Dockerfile.dev .

  script:
    - - docker run -e CI=true fmtech2014/docker-react npm run test
